name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: turing-clover-338007

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push container image
        run: |
          IMAGE_NAME="gcr.io/turing-clover-338007/aipasyoutube:latest"
          gcloud builds submit --tag $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy aipasyoutube \
            --image gcr.io/turing-clover-338007/aipasyoutube:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated

      - name: Inject
